/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* top =  1  *)
(* src = "RTL/Bit_Generator_Circuit.v:1" *)
module Bit_Generator_Circuit(clk, rst_n, seed_in, par_in, mode, lfsr_en, count_en, on_switch, total_count);
  (* src = "RTL/Bit_Generator_Circuit.v:26|RTL/Shift_Register.v:14|RTL/Shift_Register.v:23|<techmap.v>:445" *)
  wire _000_;
  (* src = "RTL/Bit_Generator_Circuit.v:26|RTL/Shift_Register.v:14|RTL/Shift_Register.v:23|<techmap.v>:445" *)
  wire _001_;
  (* src = "RTL/Bit_Generator_Circuit.v:26|RTL/Shift_Register.v:14|RTL/Shift_Register.v:23|<techmap.v>:445" *)
  wire _002_;
  (* src = "RTL/Bit_Generator_Circuit.v:26|RTL/Shift_Register.v:14|RTL/Shift_Register.v:23|<techmap.v>:445" *)
  wire _003_;
  (* src = "RTL/Bit_Generator_Circuit.v:26|RTL/Shift_Register.v:14|RTL/Shift_Register.v:23|<techmap.v>:445" *)
  wire _004_;
  (* src = "RTL/Bit_Generator_Circuit.v:26|RTL/Shift_Register.v:14|RTL/Shift_Register.v:23|<techmap.v>:445" *)
  wire _005_;
  (* src = "RTL/Bit_Generator_Circuit.v:26|RTL/Shift_Register.v:14|RTL/Shift_Register.v:23|<techmap.v>:445" *)
  wire _006_;
  (* src = "RTL/Bit_Generator_Circuit.v:26|RTL/Shift_Register.v:14|RTL/Shift_Register.v:23|<techmap.v>:445" *)
  wire _007_;
  (* src = "RTL/Bit_Generator_Circuit.v:26|RTL/Shift_Register.v:14|RTL/Shift_Register.v:23|<techmap.v>:445" *)
  wire _008_;
  (* src = "RTL/Bit_Generator_Circuit.v:26|RTL/Shift_Register.v:14|RTL/Shift_Register.v:23|<techmap.v>:445" *)
  wire _009_;
  (* src = "RTL/Bit_Generator_Circuit.v:26|RTL/Shift_Register.v:14|RTL/Shift_Register.v:23|<techmap.v>:445" *)
  wire _010_;
  (* src = "RTL/Bit_Generator_Circuit.v:26|RTL/Shift_Register.v:14|RTL/Shift_Register.v:23|<techmap.v>:445" *)
  wire _011_;
  (* src = "RTL/Bit_Generator_Circuit.v:43|RTL/Counter.v:9" *)
  wire _012_;
  (* src = "RTL/Bit_Generator_Circuit.v:43|RTL/Counter.v:9" *)
  wire _013_;
  (* src = "RTL/Bit_Generator_Circuit.v:43|RTL/Counter.v:9" *)
  wire _014_;
  (* src = "RTL/Bit_Generator_Circuit.v:43|RTL/Counter.v:9" *)
  wire _015_;
  (* src = "RTL/Bit_Generator_Circuit.v:43|RTL/Counter.v:9" *)
  wire _016_;
  (* src = "RTL/Bit_Generator_Circuit.v:43|RTL/Counter.v:9" *)
  wire _017_;
  (* src = "RTL/Bit_Generator_Circuit.v:43|RTL/Counter.v:9" *)
  wire _018_;
  (* src = "RTL/Bit_Generator_Circuit.v:43|RTL/Counter.v:9" *)
  wire _019_;
  (* src = "RTL/Bit_Generator_Circuit.v:43|RTL/Counter.v:9" *)
  wire _020_;
  (* src = "RTL/Bit_Generator_Circuit.v:43|RTL/Counter.v:9" *)
  wire _021_;
  (* src = "RTL/Bit_Generator_Circuit.v:43|RTL/Counter.v:9" *)
  wire _022_;
  (* src = "RTL/Bit_Generator_Circuit.v:43|RTL/Counter.v:9" *)
  wire _023_;
  (* src = "RTL/Bit_Generator_Circuit.v:17|RTL/LFSR.v:13" *)
  wire _024_;
  (* src = "RTL/Bit_Generator_Circuit.v:17|RTL/LFSR.v:13" *)
  wire _025_;
  (* src = "RTL/Bit_Generator_Circuit.v:17|RTL/LFSR.v:13" *)
  wire _026_;
  (* src = "RTL/Bit_Generator_Circuit.v:17|RTL/LFSR.v:13" *)
  wire _027_;
  (* src = "RTL/Bit_Generator_Circuit.v:17|RTL/LFSR.v:13" *)
  wire _028_;
  (* src = "RTL/Bit_Generator_Circuit.v:17|RTL/LFSR.v:13" *)
  wire _029_;
  (* src = "RTL/Bit_Generator_Circuit.v:17|RTL/LFSR.v:13" *)
  wire _030_;
  (* src = "RTL/Bit_Generator_Circuit.v:17|RTL/LFSR.v:13" *)
  wire _031_;
  (* src = "RTL/Bit_Generator_Circuit.v:17|RTL/LFSR.v:13" *)
  wire _032_;
  (* src = "RTL/Bit_Generator_Circuit.v:17|RTL/LFSR.v:13" *)
  wire _033_;
  (* src = "RTL/Bit_Generator_Circuit.v:17|RTL/LFSR.v:13" *)
  wire _034_;
  (* src = "RTL/Bit_Generator_Circuit.v:17|RTL/LFSR.v:13" *)
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  (* src = "RTL/Bit_Generator_Circuit.v:2" *)
  input clk;
  (* src = "RTL/Bit_Generator_Circuit.v:36|RTL/Comparator.v:2" *)
  wire [11:0] \comp.A ;
  (* src = "RTL/Bit_Generator_Circuit.v:36|RTL/Comparator.v:3" *)
  wire [11:0] \comp.B ;
  (* src = "RTL/Bit_Generator_Circuit.v:36|RTL/Comparator.v:18|RTL/priority_encoder.v:6" *)
  wire [31:0] \comp.pe1.i ;
  (* src = "RTL/Bit_Generator_Circuit.v:36|RTL/Comparator.v:24|RTL/priority_encoder.v:6" *)
  wire [31:0] \comp.pe2.i ;
  (* src = "RTL/Bit_Generator_Circuit.v:8" *)
  input count_en;
  (* src = "RTL/Bit_Generator_Circuit.v:43|RTL/Counter.v:2" *)
  wire \final_counter.clk ;
  (* src = "RTL/Bit_Generator_Circuit.v:43|RTL/Counter.v:6" *)
  reg [11:0] \final_counter.count ;
  (* src = "RTL/Bit_Generator_Circuit.v:43|RTL/Counter.v:4" *)
  wire \final_counter.on_switch ;
  (* src = "RTL/Bit_Generator_Circuit.v:43|RTL/Counter.v:3" *)
  wire \final_counter.rst_n ;
  (* src = "RTL/Bit_Generator_Circuit.v:7" *)
  input lfsr_en;
  (* src = "RTL/Bit_Generator_Circuit.v:12" *)
  wire [11:0] lfsr_out;
  (* src = "RTL/Bit_Generator_Circuit.v:6" *)
  input [1:0] mode;
  (* src = "RTL/Bit_Generator_Circuit.v:9" *)
  input on_switch;
  (* src = "RTL/Bit_Generator_Circuit.v:5" *)
  input [11:0] par_in;
  (* src = "RTL/Bit_Generator_Circuit.v:3" *)
  input rst_n;
  (* src = "RTL/Bit_Generator_Circuit.v:4" *)
  input [11:0] seed_in;
  (* src = "RTL/Bit_Generator_Circuit.v:13" *)
  wire [11:0] shift_reg_out;
  (* src = "RTL/Bit_Generator_Circuit.v:26|RTL/Shift_Register.v:2" *)
  wire \sr.clk ;
  (* src = "RTL/Bit_Generator_Circuit.v:26|RTL/Shift_Register.v:4" *)
  wire [1:0] \sr.mode ;
  (* src = "RTL/Bit_Generator_Circuit.v:26|RTL/Shift_Register.v:6" *)
  wire [11:0] \sr.parallel_in ;
  (* src = "RTL/Bit_Generator_Circuit.v:26|RTL/Shift_Register.v:7" *)
  reg [11:0] \sr.q ;
  (* src = "RTL/Bit_Generator_Circuit.v:26|RTL/Shift_Register.v:3" *)
  wire \sr.reset ;
  (* src = "RTL/Bit_Generator_Circuit.v:26|RTL/Shift_Register.v:5" *)
  wire \sr.serial_in ;
  (* src = "RTL/Bit_Generator_Circuit.v:10" *)
  output [11:0] total_count;
  (* src = "RTL/Bit_Generator_Circuit.v:17|RTL/LFSR.v:2" *)
  wire \u_lfsr.clk ;
  (* src = "RTL/Bit_Generator_Circuit.v:17|RTL/LFSR.v:4" *)
  wire \u_lfsr.en ;
  (* src = "RTL/Bit_Generator_Circuit.v:17|RTL/LFSR.v:3" *)
  wire \u_lfsr.rst_n ;
  (* src = "RTL/Bit_Generator_Circuit.v:17|RTL/LFSR.v:5" *)
  wire [11:0] \u_lfsr.seed_in ;
  (* src = "RTL/Bit_Generator_Circuit.v:17|RTL/LFSR.v:6" *)
  reg [11:0] \u_lfsr.seed_mem ;
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _206_ (
    .I(\sr.q [10]),
    .ZN(_060_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _207_ (
    .I(\sr.q [11]),
    .ZN(_061_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _208_ (
    .I(rst_n),
    .ZN(\sr.reset )
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _209_ (
    .I(\u_lfsr.seed_mem [11]),
    .ZN(_062_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _210_ (
    .I(\u_lfsr.seed_mem [6]),
    .ZN(_063_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _211_ (
    .I(\u_lfsr.seed_mem [3]),
    .ZN(_064_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _212_ (
    .I(\u_lfsr.seed_mem [1]),
    .ZN(_065_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _213_ (
    .I(\u_lfsr.seed_mem [4]),
    .ZN(_066_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _214_ (
    .I(\u_lfsr.seed_mem [5]),
    .ZN(_067_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _215_ (
    .I(\u_lfsr.seed_mem [7]),
    .ZN(_068_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _216_ (
    .I(\u_lfsr.seed_mem [8]),
    .ZN(_069_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _217_ (
    .I(\u_lfsr.seed_mem [9]),
    .ZN(_070_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _218_ (
    .I(\sr.q [7]),
    .ZN(_071_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _219_ (
    .I(\sr.q [3]),
    .ZN(_072_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _220_ (
    .I(\sr.q [2]),
    .ZN(_073_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _221_ (
    .I(\sr.q [0]),
    .ZN(_074_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _222_ (
    .I(on_switch),
    .ZN(_075_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _223_ (
    .I(mode[0]),
    .ZN(_076_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _224_ (
    .A1(_076_),
    .A2(mode[1]),
    .ZN(_077_)
  );
  gf180mcu_fd_sc_mcu7t5v0__and2_1 _225_ (
    .A1(_076_),
    .A2(mode[1]),
    .Z(_078_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _226_ (
    .A1(_077_),
    .A2(_078_),
    .ZN(_079_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _227_ (
    .A1(\sr.q [10]),
    .A2(_079_),
    .ZN(_080_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi22_1 _228_ (
    .A1(\sr.q [11]),
    .A2(_077_),
    .B1(_078_),
    .B2(par_in[10]),
    .ZN(_081_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _229_ (
    .A1(_080_),
    .A2(_081_),
    .ZN(_001_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi22_1 _230_ (
    .A1(par_in[11]),
    .A2(_078_),
    .B1(_079_),
    .B2(\sr.q [11]),
    .ZN(_082_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _231_ (
    .I(_082_),
    .ZN(_002_)
  );
  gf180mcu_fd_sc_mcu7t5v0__xor2_1 _232_ (
    .A1(\u_lfsr.seed_mem [11]),
    .A2(\u_lfsr.seed_mem [6]),
    .Z(_083_)
  );
  gf180mcu_fd_sc_mcu7t5v0__xor3_1 _233_ (
    .A1(\u_lfsr.seed_mem [3]),
    .A2(\u_lfsr.seed_mem [2]),
    .A3(_083_),
    .Z(_084_)
  );
  gf180mcu_fd_sc_mcu7t5v0__mux2_1 _234_ (
    .I0(seed_in[0]),
    .I1(_084_),
    .S(lfsr_en),
    .Z(_024_)
  );
  gf180mcu_fd_sc_mcu7t5v0__mux2_1 _235_ (
    .I0(seed_in[1]),
    .I1(\u_lfsr.seed_mem [0]),
    .S(lfsr_en),
    .Z(_027_)
  );
  gf180mcu_fd_sc_mcu7t5v0__mux2_1 _236_ (
    .I0(seed_in[2]),
    .I1(\u_lfsr.seed_mem [1]),
    .S(lfsr_en),
    .Z(_028_)
  );
  gf180mcu_fd_sc_mcu7t5v0__mux2_1 _237_ (
    .I0(seed_in[3]),
    .I1(\u_lfsr.seed_mem [2]),
    .S(lfsr_en),
    .Z(_029_)
  );
  gf180mcu_fd_sc_mcu7t5v0__mux2_1 _238_ (
    .I0(seed_in[4]),
    .I1(\u_lfsr.seed_mem [3]),
    .S(lfsr_en),
    .Z(_030_)
  );
  gf180mcu_fd_sc_mcu7t5v0__mux2_1 _239_ (
    .I0(seed_in[5]),
    .I1(\u_lfsr.seed_mem [4]),
    .S(lfsr_en),
    .Z(_031_)
  );
  gf180mcu_fd_sc_mcu7t5v0__mux2_1 _240_ (
    .I0(seed_in[6]),
    .I1(\u_lfsr.seed_mem [5]),
    .S(lfsr_en),
    .Z(_032_)
  );
  gf180mcu_fd_sc_mcu7t5v0__mux2_1 _241_ (
    .I0(seed_in[7]),
    .I1(\u_lfsr.seed_mem [6]),
    .S(lfsr_en),
    .Z(_033_)
  );
  gf180mcu_fd_sc_mcu7t5v0__mux2_1 _242_ (
    .I0(seed_in[8]),
    .I1(\u_lfsr.seed_mem [7]),
    .S(lfsr_en),
    .Z(_034_)
  );
  gf180mcu_fd_sc_mcu7t5v0__mux2_1 _243_ (
    .I0(seed_in[9]),
    .I1(\u_lfsr.seed_mem [8]),
    .S(lfsr_en),
    .Z(_035_)
  );
  gf180mcu_fd_sc_mcu7t5v0__mux2_1 _244_ (
    .I0(seed_in[10]),
    .I1(\u_lfsr.seed_mem [9]),
    .S(lfsr_en),
    .Z(_025_)
  );
  gf180mcu_fd_sc_mcu7t5v0__mux2_1 _245_ (
    .I0(seed_in[11]),
    .I1(\u_lfsr.seed_mem [10]),
    .S(lfsr_en),
    .Z(_026_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _246_ (
    .A1(rst_n),
    .A2(seed_in[0]),
    .ZN(_048_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _247_ (
    .A1(rst_n),
    .A2(seed_in[1]),
    .ZN(_051_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _248_ (
    .A1(rst_n),
    .A2(seed_in[2]),
    .ZN(_052_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _249_ (
    .A1(rst_n),
    .A2(seed_in[3]),
    .ZN(_053_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _250_ (
    .A1(rst_n),
    .A2(seed_in[4]),
    .ZN(_054_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _251_ (
    .A1(rst_n),
    .A2(seed_in[5]),
    .ZN(_055_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _252_ (
    .A1(rst_n),
    .A2(seed_in[6]),
    .ZN(_056_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _253_ (
    .A1(rst_n),
    .A2(seed_in[7]),
    .ZN(_057_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _254_ (
    .A1(rst_n),
    .A2(seed_in[8]),
    .ZN(_058_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _255_ (
    .A1(rst_n),
    .A2(seed_in[9]),
    .ZN(_059_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _256_ (
    .A1(rst_n),
    .A2(seed_in[10]),
    .ZN(_049_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _257_ (
    .A1(rst_n),
    .A2(seed_in[11]),
    .ZN(_050_)
  );
  gf180mcu_fd_sc_mcu7t5v0__and2_1 _258_ (
    .A1(\sr.reset ),
    .A2(seed_in[0]),
    .Z(_036_)
  );
  gf180mcu_fd_sc_mcu7t5v0__and2_1 _259_ (
    .A1(\sr.reset ),
    .A2(seed_in[1]),
    .Z(_039_)
  );
  gf180mcu_fd_sc_mcu7t5v0__and2_1 _260_ (
    .A1(\sr.reset ),
    .A2(seed_in[2]),
    .Z(_040_)
  );
  gf180mcu_fd_sc_mcu7t5v0__and2_1 _261_ (
    .A1(\sr.reset ),
    .A2(seed_in[3]),
    .Z(_041_)
  );
  gf180mcu_fd_sc_mcu7t5v0__and2_1 _262_ (
    .A1(\sr.reset ),
    .A2(seed_in[4]),
    .Z(_042_)
  );
  gf180mcu_fd_sc_mcu7t5v0__and2_1 _263_ (
    .A1(\sr.reset ),
    .A2(seed_in[5]),
    .Z(_043_)
  );
  gf180mcu_fd_sc_mcu7t5v0__and2_1 _264_ (
    .A1(\sr.reset ),
    .A2(seed_in[6]),
    .Z(_044_)
  );
  gf180mcu_fd_sc_mcu7t5v0__and2_1 _265_ (
    .A1(\sr.reset ),
    .A2(seed_in[7]),
    .Z(_045_)
  );
  gf180mcu_fd_sc_mcu7t5v0__and2_1 _266_ (
    .A1(\sr.reset ),
    .A2(seed_in[8]),
    .Z(_046_)
  );
  gf180mcu_fd_sc_mcu7t5v0__and2_1 _267_ (
    .A1(\sr.reset ),
    .A2(seed_in[9]),
    .Z(_047_)
  );
  gf180mcu_fd_sc_mcu7t5v0__and2_1 _268_ (
    .A1(\sr.reset ),
    .A2(seed_in[10]),
    .Z(_037_)
  );
  gf180mcu_fd_sc_mcu7t5v0__and2_1 _269_ (
    .A1(\sr.reset ),
    .A2(seed_in[11]),
    .Z(_038_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _270_ (
    .A1(_061_),
    .A2(\u_lfsr.seed_mem [11]),
    .ZN(_085_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _271_ (
    .A1(\sr.q [11]),
    .A2(_062_),
    .ZN(_086_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _272_ (
    .A1(_060_),
    .A2(\u_lfsr.seed_mem [10]),
    .ZN(_087_)
  );
  gf180mcu_fd_sc_mcu7t5v0__and2_1 _273_ (
    .A1(_070_),
    .A2(\sr.q [9]),
    .Z(_088_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _274_ (
    .A1(_087_),
    .A2(_088_),
    .ZN(_089_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _275_ (
    .A1(_069_),
    .A2(\sr.q [8]),
    .ZN(_090_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _276_ (
    .A1(_068_),
    .A2(\sr.q [7]),
    .ZN(_091_)
  );
  gf180mcu_fd_sc_mcu7t5v0__and3_1 _277_ (
    .A1(_089_),
    .A2(_090_),
    .A3(_091_),
    .Z(_092_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _278_ (
    .A1(_063_),
    .A2(\sr.q [6]),
    .ZN(_093_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _279_ (
    .I(_093_),
    .ZN(_094_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _280_ (
    .A1(_067_),
    .A2(\sr.q [5]),
    .ZN(_095_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _281_ (
    .A1(_093_),
    .A2(_095_),
    .ZN(_096_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _282_ (
    .A1(_066_),
    .A2(\sr.q [4]),
    .ZN(_097_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _283_ (
    .A1(_064_),
    .A2(\sr.q [3]),
    .ZN(_098_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _284_ (
    .A1(_097_),
    .A2(_098_),
    .ZN(_099_)
  );
  gf180mcu_fd_sc_mcu7t5v0__or2_1 _285_ (
    .A1(_096_),
    .A2(_099_),
    .Z(_100_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _286_ (
    .A1(_092_),
    .A2(_100_),
    .ZN(_101_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _287_ (
    .A1(\sr.q [11]),
    .A2(_062_),
    .ZN(_102_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _288_ (
    .A1(_061_),
    .A2(\u_lfsr.seed_mem [11]),
    .ZN(_103_)
  );
  gf180mcu_fd_sc_mcu7t5v0__and2_1 _289_ (
    .A1(_060_),
    .A2(\u_lfsr.seed_mem [10]),
    .Z(_104_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _290_ (
    .I(_104_),
    .ZN(_105_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _291_ (
    .A1(_070_),
    .A2(\sr.q [9]),
    .ZN(_106_)
  );
  gf180mcu_fd_sc_mcu7t5v0__or2_1 _292_ (
    .A1(_069_),
    .A2(\sr.q [8]),
    .Z(_107_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _293_ (
    .I(_107_),
    .ZN(_108_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _294_ (
    .A1(_068_),
    .A2(\sr.q [7]),
    .B(_107_),
    .ZN(_109_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor3_1 _295_ (
    .A1(_104_),
    .A2(_106_),
    .A3(_109_),
    .ZN(_110_)
  );
  gf180mcu_fd_sc_mcu7t5v0__or2_1 _296_ (
    .A1(_063_),
    .A2(\sr.q [6]),
    .Z(_111_)
  );
  gf180mcu_fd_sc_mcu7t5v0__or2_1 _297_ (
    .A1(_067_),
    .A2(\sr.q [5]),
    .Z(_112_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _298_ (
    .A1(_111_),
    .A2(_112_),
    .ZN(_113_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _299_ (
    .A1(_066_),
    .A2(\sr.q [4]),
    .ZN(_114_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai22_1 _300_ (
    .A1(_066_),
    .A2(\sr.q [4]),
    .B1(\sr.q [3]),
    .B2(_064_),
    .ZN(_115_)
  );
  gf180mcu_fd_sc_mcu7t5v0__or2_1 _301_ (
    .A1(_113_),
    .A2(_115_),
    .Z(_116_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _302_ (
    .A1(_110_),
    .A2(_116_),
    .ZN(_117_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi221_1 _303_ (
    .A1(_092_),
    .A2(_100_),
    .B1(_103_),
    .B2(_117_),
    .C(_085_),
    .ZN(_118_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _304_ (
    .A1(_086_),
    .A2(_092_),
    .ZN(_119_)
  );
  gf180mcu_fd_sc_mcu7t5v0__and2_1 _305_ (
    .A1(_103_),
    .A2(_110_),
    .Z(_120_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _306_ (
    .A1(_119_),
    .A2(_120_),
    .ZN(_121_)
  );
  gf180mcu_fd_sc_mcu7t5v0__xnor2_1 _307_ (
    .A1(_119_),
    .A2(_120_),
    .ZN(_122_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi221_1 _308_ (
    .A1(_086_),
    .A2(_101_),
    .B1(_110_),
    .B2(_116_),
    .C(_102_),
    .ZN(_123_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor3_1 _309_ (
    .A1(_118_),
    .A2(_122_),
    .A3(_123_),
    .ZN(_124_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _310_ (
    .I(_124_),
    .ZN(_125_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _311_ (
    .A1(\u_lfsr.seed_mem [2]),
    .A2(_073_),
    .ZN(_126_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _312_ (
    .A1(_065_),
    .A2(\sr.q [1]),
    .B(_126_),
    .ZN(_127_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _313_ (
    .A1(_099_),
    .A2(_127_),
    .ZN(_128_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai211_1 _314_ (
    .A1(_096_),
    .A2(_128_),
    .B(_090_),
    .C(_091_),
    .ZN(_129_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _315_ (
    .A1(_089_),
    .A2(_129_),
    .B(_085_),
    .ZN(_130_)
  );
  gf180mcu_fd_sc_mcu7t5v0__or2_1 _316_ (
    .A1(_065_),
    .A2(\sr.q [1]),
    .Z(_131_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _317_ (
    .A1(\u_lfsr.seed_mem [2]),
    .A2(_073_),
    .ZN(_132_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _318_ (
    .A1(_131_),
    .A2(_132_),
    .B(_115_),
    .ZN(_133_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _319_ (
    .A1(_113_),
    .A2(_133_),
    .ZN(_134_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _320_ (
    .A1(_109_),
    .A2(_134_),
    .ZN(_135_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai31_1 _321_ (
    .A1(_104_),
    .A2(_106_),
    .A3(_135_),
    .B(_103_),
    .ZN(_136_)
  );
  gf180mcu_fd_sc_mcu7t5v0__or2_1 _322_ (
    .A1(_130_),
    .A2(_136_),
    .Z(_137_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi211_1 _323_ (
    .A1(_065_),
    .A2(\sr.q [1]),
    .B(_074_),
    .C(\u_lfsr.seed_mem [0]),
    .ZN(_138_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _324_ (
    .A1(_126_),
    .A2(_138_),
    .B(_098_),
    .ZN(_139_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi22_1 _325_ (
    .A1(_067_),
    .A2(\sr.q [5]),
    .B1(_097_),
    .B2(_139_),
    .ZN(_140_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _326_ (
    .A1(_094_),
    .A2(_140_),
    .B(_091_),
    .ZN(_141_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _327_ (
    .A1(_090_),
    .A2(_141_),
    .B(_088_),
    .ZN(_142_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _328_ (
    .A1(_087_),
    .A2(_142_),
    .B(_086_),
    .ZN(_143_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai211_1 _329_ (
    .A1(_065_),
    .A2(\sr.q [1]),
    .B(_074_),
    .C(\u_lfsr.seed_mem [0]),
    .ZN(_144_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi22_1 _330_ (
    .A1(\u_lfsr.seed_mem [3]),
    .A2(_072_),
    .B1(_132_),
    .B2(_144_),
    .ZN(_145_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _331_ (
    .A1(_114_),
    .A2(_145_),
    .B(_112_),
    .ZN(_146_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi22_1 _332_ (
    .A1(\u_lfsr.seed_mem [7]),
    .A2(_071_),
    .B1(_111_),
    .B2(_146_),
    .ZN(_147_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai22_1 _333_ (
    .A1(_070_),
    .A2(\sr.q [9]),
    .B1(_108_),
    .B2(_147_),
    .ZN(_148_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _334_ (
    .A1(_105_),
    .A2(_148_),
    .B(_102_),
    .ZN(_149_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _335_ (
    .A1(_130_),
    .A2(_136_),
    .ZN(_150_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _336_ (
    .A1(_143_),
    .A2(_149_),
    .B(_150_),
    .ZN(_151_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _337_ (
    .A1(_137_),
    .A2(_151_),
    .B(_125_),
    .ZN(_152_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _338_ (
    .A1(_118_),
    .A2(_121_),
    .ZN(_153_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _339_ (
    .A1(_119_),
    .A2(_120_),
    .B(_153_),
    .ZN(_154_)
  );
  gf180mcu_fd_sc_mcu7t5v0__and2_1 _340_ (
    .A1(_143_),
    .A2(_149_),
    .Z(_155_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _341_ (
    .A1(_124_),
    .A2(_137_),
    .ZN(_156_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai32_1 _342_ (
    .A1(_151_),
    .A2(_155_),
    .A3(_156_),
    .B1(_152_),
    .B2(_154_),
    .ZN(_157_)
  );
  gf180mcu_fd_sc_mcu7t5v0__and2_1 _343_ (
    .A1(count_en),
    .A2(_157_),
    .Z(_158_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _344_ (
    .A1(\final_counter.count [0]),
    .A2(_158_),
    .B(on_switch),
    .ZN(_159_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _345_ (
    .A1(\final_counter.count [0]),
    .A2(_158_),
    .B(_159_),
    .ZN(_012_)
  );
  gf180mcu_fd_sc_mcu7t5v0__and2_1 _346_ (
    .A1(\final_counter.count [0]),
    .A2(\final_counter.count [1]),
    .Z(_160_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _347_ (
    .A1(\final_counter.count [0]),
    .A2(_158_),
    .B(\final_counter.count [1]),
    .ZN(_161_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi211_1 _348_ (
    .A1(_158_),
    .A2(_160_),
    .B(_161_),
    .C(_075_),
    .ZN(_015_)
  );
  gf180mcu_fd_sc_mcu7t5v0__and3_1 _349_ (
    .A1(\final_counter.count [2]),
    .A2(_158_),
    .A3(_160_),
    .Z(_162_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _350_ (
    .A1(_158_),
    .A2(_160_),
    .B(\final_counter.count [2]),
    .ZN(_163_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor3_1 _351_ (
    .A1(_075_),
    .A2(_162_),
    .A3(_163_),
    .ZN(_016_)
  );
  gf180mcu_fd_sc_mcu7t5v0__and3_1 _352_ (
    .A1(\final_counter.count [2]),
    .A2(\final_counter.count [3]),
    .A3(_160_),
    .Z(_164_)
  );
  gf180mcu_fd_sc_mcu7t5v0__and2_1 _353_ (
    .A1(_158_),
    .A2(_164_),
    .Z(_165_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _354_ (
    .A1(\final_counter.count [3]),
    .A2(_162_),
    .B(on_switch),
    .ZN(_166_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _355_ (
    .A1(_165_),
    .A2(_166_),
    .ZN(_017_)
  );
  gf180mcu_fd_sc_mcu7t5v0__and3_1 _356_ (
    .A1(\final_counter.count [4]),
    .A2(_158_),
    .A3(_164_),
    .Z(_167_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _357_ (
    .A1(\final_counter.count [4]),
    .A2(_165_),
    .B(on_switch),
    .ZN(_168_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _358_ (
    .A1(_167_),
    .A2(_168_),
    .ZN(_018_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _359_ (
    .A1(\final_counter.count [5]),
    .A2(_167_),
    .B(on_switch),
    .ZN(_169_)
  );
  gf180mcu_fd_sc_mcu7t5v0__and4_1 _360_ (
    .A1(\final_counter.count [4]),
    .A2(\final_counter.count [5]),
    .A3(_158_),
    .A4(_164_),
    .Z(_170_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _361_ (
    .A1(_169_),
    .A2(_170_),
    .ZN(_019_)
  );
  gf180mcu_fd_sc_mcu7t5v0__and3_1 _362_ (
    .A1(\final_counter.count [4]),
    .A2(\final_counter.count [5]),
    .A3(\final_counter.count [6]),
    .Z(_171_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _363_ (
    .A1(\final_counter.count [6]),
    .A2(_170_),
    .B(on_switch),
    .ZN(_172_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _364_ (
    .A1(\final_counter.count [6]),
    .A2(_170_),
    .B(_172_),
    .ZN(_020_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _365_ (
    .A1(\final_counter.count [4]),
    .A2(\final_counter.count [6]),
    .ZN(_173_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand4_1 _366_ (
    .A1(\final_counter.count [2]),
    .A2(\final_counter.count [3]),
    .A3(\final_counter.count [5]),
    .A4(_160_),
    .ZN(_174_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _367_ (
    .A1(_173_),
    .A2(_174_),
    .ZN(_175_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _368_ (
    .A1(_158_),
    .A2(_175_),
    .B(\final_counter.count [7]),
    .ZN(_176_)
  );
  gf180mcu_fd_sc_mcu7t5v0__and4_1 _369_ (
    .A1(\final_counter.count [7]),
    .A2(_158_),
    .A3(_164_),
    .A4(_171_),
    .Z(_177_)
  );
  gf180mcu_fd_sc_mcu7t5v0__and4_1 _370_ (
    .A1(count_en),
    .A2(\final_counter.count [7]),
    .A3(_157_),
    .A4(_175_),
    .Z(_178_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor3_1 _371_ (
    .A1(_075_),
    .A2(_176_),
    .A3(_177_),
    .ZN(_021_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _372_ (
    .A1(\final_counter.count [8]),
    .A2(_178_),
    .B(on_switch),
    .ZN(_179_)
  );
  gf180mcu_fd_sc_mcu7t5v0__and2_1 _373_ (
    .A1(\final_counter.count [8]),
    .A2(_178_),
    .Z(_180_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _374_ (
    .A1(_179_),
    .A2(_180_),
    .ZN(_022_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _375_ (
    .A1(\final_counter.count [9]),
    .A2(_180_),
    .B(on_switch),
    .ZN(_181_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _376_ (
    .A1(\final_counter.count [9]),
    .A2(_180_),
    .B(_181_),
    .ZN(_023_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _377_ (
    .A1(\final_counter.count [9]),
    .A2(_180_),
    .B(\final_counter.count [10]),
    .ZN(_182_)
  );
  gf180mcu_fd_sc_mcu7t5v0__and4_1 _378_ (
    .A1(\final_counter.count [8]),
    .A2(\final_counter.count [9]),
    .A3(\final_counter.count [10]),
    .A4(_177_),
    .Z(_183_)
  );
  gf180mcu_fd_sc_mcu7t5v0__and4_1 _379_ (
    .A1(\final_counter.count [8]),
    .A2(\final_counter.count [9]),
    .A3(\final_counter.count [10]),
    .A4(_178_),
    .Z(_184_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor3_1 _380_ (
    .A1(_075_),
    .A2(_182_),
    .A3(_183_),
    .ZN(_013_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _381_ (
    .A1(\final_counter.count [11]),
    .A2(_184_),
    .B(on_switch),
    .ZN(_185_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _382_ (
    .A1(\final_counter.count [11]),
    .A2(_183_),
    .B(_185_),
    .ZN(_014_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _383_ (
    .A1(\sr.q [0]),
    .A2(_079_),
    .ZN(_186_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi22_1 _384_ (
    .A1(\sr.q [1]),
    .A2(_077_),
    .B1(_078_),
    .B2(par_in[0]),
    .ZN(_187_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _385_ (
    .A1(_186_),
    .A2(_187_),
    .ZN(_000_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _386_ (
    .A1(\sr.q [1]),
    .A2(_079_),
    .ZN(_188_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi22_1 _387_ (
    .A1(\sr.q [2]),
    .A2(_077_),
    .B1(_078_),
    .B2(par_in[1]),
    .ZN(_189_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _388_ (
    .A1(_188_),
    .A2(_189_),
    .ZN(_003_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _389_ (
    .A1(\sr.q [2]),
    .A2(_079_),
    .ZN(_190_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi22_1 _390_ (
    .A1(\sr.q [3]),
    .A2(_077_),
    .B1(_078_),
    .B2(par_in[2]),
    .ZN(_191_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _391_ (
    .A1(_190_),
    .A2(_191_),
    .ZN(_004_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _392_ (
    .A1(\sr.q [3]),
    .A2(_079_),
    .ZN(_192_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi22_1 _393_ (
    .A1(\sr.q [4]),
    .A2(_077_),
    .B1(_078_),
    .B2(par_in[3]),
    .ZN(_193_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _394_ (
    .A1(_192_),
    .A2(_193_),
    .ZN(_005_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _395_ (
    .A1(\sr.q [4]),
    .A2(_079_),
    .ZN(_194_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi22_1 _396_ (
    .A1(\sr.q [5]),
    .A2(_077_),
    .B1(_078_),
    .B2(par_in[4]),
    .ZN(_195_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _397_ (
    .A1(_194_),
    .A2(_195_),
    .ZN(_006_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _398_ (
    .A1(\sr.q [5]),
    .A2(_079_),
    .ZN(_196_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi22_1 _399_ (
    .A1(\sr.q [6]),
    .A2(_077_),
    .B1(_078_),
    .B2(par_in[5]),
    .ZN(_197_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _400_ (
    .A1(_196_),
    .A2(_197_),
    .ZN(_007_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _401_ (
    .A1(\sr.q [6]),
    .A2(_079_),
    .ZN(_198_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi22_1 _402_ (
    .A1(\sr.q [7]),
    .A2(_077_),
    .B1(_078_),
    .B2(par_in[6]),
    .ZN(_199_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _403_ (
    .A1(_198_),
    .A2(_199_),
    .ZN(_008_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _404_ (
    .A1(\sr.q [7]),
    .A2(_079_),
    .ZN(_200_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi22_1 _405_ (
    .A1(\sr.q [8]),
    .A2(_077_),
    .B1(_078_),
    .B2(par_in[7]),
    .ZN(_201_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _406_ (
    .A1(_200_),
    .A2(_201_),
    .ZN(_009_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _407_ (
    .A1(\sr.q [8]),
    .A2(_079_),
    .ZN(_202_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi22_1 _408_ (
    .A1(\sr.q [9]),
    .A2(_077_),
    .B1(_078_),
    .B2(par_in[8]),
    .ZN(_203_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _409_ (
    .A1(_202_),
    .A2(_203_),
    .ZN(_010_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _410_ (
    .A1(\sr.q [9]),
    .A2(_079_),
    .ZN(_204_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi22_1 _411_ (
    .A1(\sr.q [10]),
    .A2(_077_),
    .B1(_078_),
    .B2(par_in[9]),
    .ZN(_205_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _412_ (
    .A1(_204_),
    .A2(_205_),
    .ZN(_011_)
  );
  (* src = "RTL/Bit_Generator_Circuit.v:17|RTL/LFSR.v:13" *)
  always @(posedge clk or posedge _036_ or posedge _048_)
    if (_048_)
      \u_lfsr.seed_mem [0] <= 0;
    else if (_036_)
      \u_lfsr.seed_mem [0] <= 1;
    else
      \u_lfsr.seed_mem [0] <= _024_;
  (* src = "RTL/Bit_Generator_Circuit.v:17|RTL/LFSR.v:13" *)
  always @(posedge clk or posedge _039_ or posedge _051_)
    if (_051_)
      \u_lfsr.seed_mem [1] <= 0;
    else if (_039_)
      \u_lfsr.seed_mem [1] <= 1;
    else
      \u_lfsr.seed_mem [1] <= _027_;
  (* src = "RTL/Bit_Generator_Circuit.v:17|RTL/LFSR.v:13" *)
  always @(posedge clk or posedge _040_ or posedge _052_)
    if (_052_)
      \u_lfsr.seed_mem [2] <= 0;
    else if (_040_)
      \u_lfsr.seed_mem [2] <= 1;
    else
      \u_lfsr.seed_mem [2] <= _028_;
  (* src = "RTL/Bit_Generator_Circuit.v:17|RTL/LFSR.v:13" *)
  always @(posedge clk or posedge _041_ or posedge _053_)
    if (_053_)
      \u_lfsr.seed_mem [3] <= 0;
    else if (_041_)
      \u_lfsr.seed_mem [3] <= 1;
    else
      \u_lfsr.seed_mem [3] <= _029_;
  (* src = "RTL/Bit_Generator_Circuit.v:17|RTL/LFSR.v:13" *)
  always @(posedge clk or posedge _042_ or posedge _054_)
    if (_054_)
      \u_lfsr.seed_mem [4] <= 0;
    else if (_042_)
      \u_lfsr.seed_mem [4] <= 1;
    else
      \u_lfsr.seed_mem [4] <= _030_;
  (* src = "RTL/Bit_Generator_Circuit.v:17|RTL/LFSR.v:13" *)
  always @(posedge clk or posedge _043_ or posedge _055_)
    if (_055_)
      \u_lfsr.seed_mem [5] <= 0;
    else if (_043_)
      \u_lfsr.seed_mem [5] <= 1;
    else
      \u_lfsr.seed_mem [5] <= _031_;
  (* src = "RTL/Bit_Generator_Circuit.v:17|RTL/LFSR.v:13" *)
  always @(posedge clk or posedge _044_ or posedge _056_)
    if (_056_)
      \u_lfsr.seed_mem [6] <= 0;
    else if (_044_)
      \u_lfsr.seed_mem [6] <= 1;
    else
      \u_lfsr.seed_mem [6] <= _032_;
  (* src = "RTL/Bit_Generator_Circuit.v:17|RTL/LFSR.v:13" *)
  always @(posedge clk or posedge _045_ or posedge _057_)
    if (_057_)
      \u_lfsr.seed_mem [7] <= 0;
    else if (_045_)
      \u_lfsr.seed_mem [7] <= 1;
    else
      \u_lfsr.seed_mem [7] <= _033_;
  (* src = "RTL/Bit_Generator_Circuit.v:17|RTL/LFSR.v:13" *)
  always @(posedge clk or posedge _046_ or posedge _058_)
    if (_058_)
      \u_lfsr.seed_mem [8] <= 0;
    else if (_046_)
      \u_lfsr.seed_mem [8] <= 1;
    else
      \u_lfsr.seed_mem [8] <= _034_;
  (* src = "RTL/Bit_Generator_Circuit.v:17|RTL/LFSR.v:13" *)
  always @(posedge clk or posedge _047_ or posedge _059_)
    if (_059_)
      \u_lfsr.seed_mem [9] <= 0;
    else if (_047_)
      \u_lfsr.seed_mem [9] <= 1;
    else
      \u_lfsr.seed_mem [9] <= _035_;
  (* src = "RTL/Bit_Generator_Circuit.v:17|RTL/LFSR.v:13" *)
  always @(posedge clk or posedge _037_ or posedge _049_)
    if (_049_)
      \u_lfsr.seed_mem [10] <= 0;
    else if (_037_)
      \u_lfsr.seed_mem [10] <= 1;
    else
      \u_lfsr.seed_mem [10] <= _025_;
  (* src = "RTL/Bit_Generator_Circuit.v:17|RTL/LFSR.v:13" *)
  always @(posedge clk or posedge _038_ or posedge _050_)
    if (_050_)
      \u_lfsr.seed_mem [11] <= 0;
    else if (_038_)
      \u_lfsr.seed_mem [11] <= 1;
    else
      \u_lfsr.seed_mem [11] <= _026_;
  (* src = "RTL/Bit_Generator_Circuit.v:26|RTL/Shift_Register.v:10" *)
  always @(posedge clk or posedge \sr.reset )
    if (\sr.reset )
      \sr.q [0] <= 0;
    else
      \sr.q [0] <= _000_;
  (* src = "RTL/Bit_Generator_Circuit.v:26|RTL/Shift_Register.v:10" *)
  always @(posedge clk or posedge \sr.reset )
    if (\sr.reset )
      \sr.q [1] <= 0;
    else
      \sr.q [1] <= _003_;
  (* src = "RTL/Bit_Generator_Circuit.v:26|RTL/Shift_Register.v:10" *)
  always @(posedge clk or posedge \sr.reset )
    if (\sr.reset )
      \sr.q [2] <= 0;
    else
      \sr.q [2] <= _004_;
  (* src = "RTL/Bit_Generator_Circuit.v:26|RTL/Shift_Register.v:10" *)
  always @(posedge clk or posedge \sr.reset )
    if (\sr.reset )
      \sr.q [3] <= 0;
    else
      \sr.q [3] <= _005_;
  (* src = "RTL/Bit_Generator_Circuit.v:26|RTL/Shift_Register.v:10" *)
  always @(posedge clk or posedge \sr.reset )
    if (\sr.reset )
      \sr.q [4] <= 0;
    else
      \sr.q [4] <= _006_;
  (* src = "RTL/Bit_Generator_Circuit.v:26|RTL/Shift_Register.v:10" *)
  always @(posedge clk or posedge \sr.reset )
    if (\sr.reset )
      \sr.q [5] <= 0;
    else
      \sr.q [5] <= _007_;
  (* src = "RTL/Bit_Generator_Circuit.v:26|RTL/Shift_Register.v:10" *)
  always @(posedge clk or posedge \sr.reset )
    if (\sr.reset )
      \sr.q [6] <= 0;
    else
      \sr.q [6] <= _008_;
  (* src = "RTL/Bit_Generator_Circuit.v:26|RTL/Shift_Register.v:10" *)
  always @(posedge clk or posedge \sr.reset )
    if (\sr.reset )
      \sr.q [7] <= 0;
    else
      \sr.q [7] <= _009_;
  (* src = "RTL/Bit_Generator_Circuit.v:26|RTL/Shift_Register.v:10" *)
  always @(posedge clk or posedge \sr.reset )
    if (\sr.reset )
      \sr.q [8] <= 0;
    else
      \sr.q [8] <= _010_;
  (* src = "RTL/Bit_Generator_Circuit.v:26|RTL/Shift_Register.v:10" *)
  always @(posedge clk or posedge \sr.reset )
    if (\sr.reset )
      \sr.q [9] <= 0;
    else
      \sr.q [9] <= _011_;
  (* src = "RTL/Bit_Generator_Circuit.v:26|RTL/Shift_Register.v:10" *)
  always @(posedge clk or posedge \sr.reset )
    if (\sr.reset )
      \sr.q [10] <= 0;
    else
      \sr.q [10] <= _001_;
  (* src = "RTL/Bit_Generator_Circuit.v:26|RTL/Shift_Register.v:10" *)
  always @(posedge clk or posedge \sr.reset )
    if (\sr.reset )
      \sr.q [11] <= 0;
    else
      \sr.q [11] <= _002_;
  (* src = "RTL/Bit_Generator_Circuit.v:43|RTL/Counter.v:9" *)
  always @(posedge clk or negedge rst_n)
    if (!rst_n)
      \final_counter.count [0] <= 0;
    else
      \final_counter.count [0] <= _012_;
  (* src = "RTL/Bit_Generator_Circuit.v:43|RTL/Counter.v:9" *)
  always @(posedge clk or negedge rst_n)
    if (!rst_n)
      \final_counter.count [1] <= 0;
    else
      \final_counter.count [1] <= _015_;
  (* src = "RTL/Bit_Generator_Circuit.v:43|RTL/Counter.v:9" *)
  always @(posedge clk or negedge rst_n)
    if (!rst_n)
      \final_counter.count [2] <= 0;
    else
      \final_counter.count [2] <= _016_;
  (* src = "RTL/Bit_Generator_Circuit.v:43|RTL/Counter.v:9" *)
  always @(posedge clk or negedge rst_n)
    if (!rst_n)
      \final_counter.count [3] <= 0;
    else
      \final_counter.count [3] <= _017_;
  (* src = "RTL/Bit_Generator_Circuit.v:43|RTL/Counter.v:9" *)
  always @(posedge clk or negedge rst_n)
    if (!rst_n)
      \final_counter.count [4] <= 0;
    else
      \final_counter.count [4] <= _018_;
  (* src = "RTL/Bit_Generator_Circuit.v:43|RTL/Counter.v:9" *)
  always @(posedge clk or negedge rst_n)
    if (!rst_n)
      \final_counter.count [5] <= 0;
    else
      \final_counter.count [5] <= _019_;
  (* src = "RTL/Bit_Generator_Circuit.v:43|RTL/Counter.v:9" *)
  always @(posedge clk or negedge rst_n)
    if (!rst_n)
      \final_counter.count [6] <= 0;
    else
      \final_counter.count [6] <= _020_;
  (* src = "RTL/Bit_Generator_Circuit.v:43|RTL/Counter.v:9" *)
  always @(posedge clk or negedge rst_n)
    if (!rst_n)
      \final_counter.count [7] <= 0;
    else
      \final_counter.count [7] <= _021_;
  (* src = "RTL/Bit_Generator_Circuit.v:43|RTL/Counter.v:9" *)
  always @(posedge clk or negedge rst_n)
    if (!rst_n)
      \final_counter.count [8] <= 0;
    else
      \final_counter.count [8] <= _022_;
  (* src = "RTL/Bit_Generator_Circuit.v:43|RTL/Counter.v:9" *)
  always @(posedge clk or negedge rst_n)
    if (!rst_n)
      \final_counter.count [9] <= 0;
    else
      \final_counter.count [9] <= _023_;
  (* src = "RTL/Bit_Generator_Circuit.v:43|RTL/Counter.v:9" *)
  always @(posedge clk or negedge rst_n)
    if (!rst_n)
      \final_counter.count [10] <= 0;
    else
      \final_counter.count [10] <= _013_;
  (* src = "RTL/Bit_Generator_Circuit.v:43|RTL/Counter.v:9" *)
  always @(posedge clk or negedge rst_n)
    if (!rst_n)
      \final_counter.count [11] <= 0;
    else
      \final_counter.count [11] <= _014_;
  assign \comp.A  = \u_lfsr.seed_mem ;
  assign \comp.B  = \sr.q ;
  assign \comp.pe1.i  = 32'd12;
  assign \comp.pe2.i  = 32'd12;
  assign \final_counter.clk  = clk;
  assign \final_counter.on_switch  = on_switch;
  assign \final_counter.rst_n  = rst_n;
  assign lfsr_out = \u_lfsr.seed_mem ;
  assign shift_reg_out = \sr.q ;
  assign \sr.clk  = clk;
  assign \sr.mode  = mode;
  assign \sr.parallel_in  = par_in;
  assign \sr.serial_in  = 1'h0;
  assign total_count = \final_counter.count ;
  assign \u_lfsr.clk  = clk;
  assign \u_lfsr.en  = lfsr_en;
  assign \u_lfsr.rst_n  = rst_n;
  assign \u_lfsr.seed_in  = seed_in;
endmodule
