#include <iostream>
#include <memory>
#include <cstdlib>
#include <cassert>
#include "VComparator.h"  // Auto-generated by Verilator
#include "verilated.h"
#include "verilated_vcd_c.h" // Required for Waveform (VCD) tracing

// Helper function to apply stimulus and verify outputs
void run_test_case(VComparator* top, VerilatedVcdC* tfp, uint64_t &sim_time, uint16_t val_A, uint16_t val_B, bool expected_x) {
    // 1. Assign inputs (masking to ensure 12-bit constraints)
    top->A = val_A & 0xFFF; 
    top->B = val_B & 0xFFF;

    // 2. Evaluate combinational logic
    top->eval();

    // Dump current signals into the waveform file
    if (tfp) tfp->dump(sim_time);
    sim_time++; // Advance simulation time

    // 3. Display results in hex and decimal formats
    std::cout << "Time: " << sim_time 
              << " | A = " << top->A << " (0x" << std::hex << top->A << ")"
              << " | B = " << top->B << " (0x" << std::hex << top->B << ")"
              << " | Output x = " << (int)top->x 
              << " | Expected = " << expected_x << std::dec << std::endl;

    // Self-checking mechanism: Exit on mismatch
    if (top->x != expected_x) {
        std::cerr << "--- TEST FAILED! Mismatch detected ---" << std::endl;
        if (tfp) tfp->close();
        exit(EXIT_FAILURE);
    }
}

int main(int argc, char** argv) {
    // Initialize Verilator arguments
    Verilated::commandArgs(argc, argv);

    // Instantiate the top-level module
    VComparator* top = new VComparator;

    // Enable waveform tracing
    Verilated::traceEverOn(true);
    VerilatedVcdC* tfp = new VerilatedVcdC;
    top->trace(tfp, 99); 
    tfp->open("waveform.vcd"); // Waveform data will be saved here

    uint64_t sim_time = 0; // Simulation time counter

    std::cout << "========================================" << std::endl;
    std::cout << "Starting Verilator Verification for Comparator..." << std::endl;
    std::cout << "========================================" << std::endl;

    // --- Test Case 1: Equal values (x should be 0) ---
    run_test_case(top, tfp, sim_time, 500, 500, 0);

    // --- Test Case 2: A > B where A has higher MSB (x should be 1) ---
    run_test_case(top, tfp, sim_time, 2048, 2047, 1);

    // --- Test Case 3: A < B where B has higher MSB (x should be 0) ---
    run_test_case(top, tfp, sim_time, 255, 256, 0);

    // --- Test Case 4: Random large values (A > B, x should be 1) ---
    run_test_case(top, tfp, sim_time, 4095, 2048, 1);

    // --- Test Case 5: Random small values (A < B, x should be 0) ---
    run_test_case(top, tfp, sim_time, 10, 4000, 0);

    // --- Test Case 6: Edge case where A is max and B is min (x should be 1) ---
    run_test_case(top, tfp, sim_time, 4095, 0, 1);

    std::cout << "========================================" << std::endl;
    std::cout << "ALL TEST CASES PASSED SUCCESSFULLY! (Total: " << sim_time << " cycles)" << std::endl;
    std::cout << "========================================" << std::endl;

    // Cleanup memory and close waveform trace
    tfp->close();
    delete top;
    delete tfp;
    return 0;
}